//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA2QBookSvc.DataAccessBDSPub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArOpenItem
    {
        public int Id { get; set; }
        public int CustomerNumber { get; set; }
        public int TransIdNumber { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string TransType { get; set; }
        public int SalesOrderNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public int SalesRepNumber { get; set; }
        public string CreditTerms { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public int LastPaymentIdNumber { get; set; }
        public string LastPaymentType { get; set; }
        public Nullable<decimal> LastPaymentAmount { get; set; }
        public Nullable<decimal> TransTaxAmt { get; set; }
        public Nullable<decimal> TransTotalAmt { get; set; }
        public Nullable<decimal> TransBalance { get; set; }
        public Nullable<decimal> TransDiscountAmt { get; set; }
        public Nullable<decimal> TransAdjustAmt { get; set; }
        public Nullable<decimal> TransBaseCommissionAmt { get; set; }
        public Nullable<decimal> TransSplitCommissionAmt { get; set; }
        public int OrigCustomerNumber { get; set; }
    }
}
