//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA2QBookSvc.DataAccessBDSPub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
        }
    
        public int Id { get; set; }
        public int CustomerNumber { get; set; }
        public string CompanyName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumberMain { get; set; }
        public string ShipToCompanyName { get; set; }
        public string ShipToAddressLine1 { get; set; }
        public string ShipToAddressLine2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToPostalCode { get; set; }
        public string ShipToPhone { get; set; }
        public string AlphaSortCompanyName { get; set; }
        public string OwnersName { get; set; }
        public string SalesContact { get; set; }
        public string PayablesContact { get; set; }
        public Nullable<int> SalesRepNumber { get; set; }
        public Nullable<int> SalesRepCommissionRate { get; set; }
        public Nullable<int> DeliveryRoute { get; set; }
        public string SalesTaxingAuthority { get; set; }
        public Nullable<double> SalesTaxRate { get; set; }
        public string ResalePermitNumber { get; set; }
        public Nullable<int> BillToCustomerNumber { get; set; }
        public string UseBillToAddress { get; set; }
        public string PostToBillToAddress { get; set; }
        public Nullable<int> UseThisPriceList { get; set; }
        public string PricingLevel { get; set; }
        public string CreditTerms { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<System.DateTime> DateCreditLimitSet { get; set; }
        public string SendStatements { get; set; }
        public string AssessServiceCharge { get; set; }
        public string SendDelinquentLetter { get; set; }
        public Nullable<System.DateTime> DateAccountCreated { get; set; }
        public Nullable<decimal> HighestBalanceEver { get; set; }
        public Nullable<System.DateTime> DateHighestBalanceEver { get; set; }
        public Nullable<int> LastSalesOrderNumber { get; set; }
        public Nullable<decimal> ARBalance { get; set; }
        public Nullable<decimal> ARBalancePeriodCurrent { get; set; }
        public Nullable<decimal> ARBalancePeriod1 { get; set; }
        public Nullable<decimal> ARBalancePeriod2 { get; set; }
        public Nullable<decimal> ARBalancePeriod3 { get; set; }
        public Nullable<decimal> ARBalancePeriod4 { get; set; }
        public Nullable<decimal> ARBalanceOpenOrders { get; set; }
        public Nullable<int> NumberOfOpenOrders { get; set; }
        public string CustomerSicCode { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public string GeneralComments { get; set; }
        public string SalesOrderRemarks { get; set; }
        public string PrintSalesOrderRemarks { get; set; }
        public string CustomerIsActive { get; set; }
        public string PhoneNumberFax { get; set; }
        public string PrintAddressLabels { get; set; }
        public string SyscoCustomerCode { get; set; }
        public Nullable<double> SyscoRate1 { get; set; }
        public Nullable<double> SyscoRate2 { get; set; }
        public string CustomerVendorNumber { get; set; }
        public Nullable<double> DiscountPercentAllowed { get; set; }
        public string EmailAddressSalesReports { get; set; }
        public string EmailPriceListToCustomer { get; set; }
        public string EmailPriceListFormat { get; set; }
        public string EmailAddressPriceList1 { get; set; }
        public string EmailAddressPriceList2 { get; set; }
        public string EmailAddressPriceList3 { get; set; }
        public string EmailAddressPriceList4 { get; set; }
        public string EmailAddressPriceList5 { get; set; }
        public string EmailAddressSalesReport1 { get; set; }
        public string EmailAddressSalesReport2 { get; set; }
        public string EmailAddressSalesReport3 { get; set; }
        public string EmailAddressSalesReport4 { get; set; }
        public string EmailAddressSalesReport5 { get; set; }
        public string PrintPriceLists { get; set; }
        public string EmailStatementsToCustomer { get; set; }
        public string EmailAddressStatements1 { get; set; }
        public string EmailAddressStatements2 { get; set; }
        public string EmailAddressStatements3 { get; set; }
        public string FaxPriceListToCustomer { get; set; }
        public string FaxPriceListPhoneNumber1 { get; set; }
        public string FaxPriceListPhoneNumber2 { get; set; }
        public string FaxPriceListPhoneNumber3 { get; set; }
        public string PrintStatementsForCustomer { get; set; }
        public string FaxStatementToCustomer { get; set; }
        public string FaxStatementNumber1 { get; set; }
        public string FaxStatementNumber2 { get; set; }
        public string FaxStatementNumber3 { get; set; }
        public string AssessFuelSurcharge { get; set; }
        public string PriceListTemplateToUse { get; set; }
        public string PLTemplateProductColumn { get; set; }
        public string PLTemplatePriceColumn { get; set; }
        public string PLTemplateDescripColumn { get; set; }
        public string PLTemplateUnitDescColumn { get; set; }
        public string PLTemplatePackDescColumn { get; set; }
        public string PLTemplateDateColumn { get; set; }
        public string PLTemplateDateRow { get; set; }
        public Nullable<int> SalesRepId { get; set; }
        public string PresentInSourceDBF { get; set; }
        public Nullable<System.DateTime> DateLastSalesOrder { get; set; }
        public Nullable<int> PeriodsUsed { get; set; }
        public Nullable<decimal> Period01MovingAverageSales { get; set; }
        public Nullable<decimal> Period02MovingAverageSales { get; set; }
        public Nullable<decimal> Period03MovingAverageSales { get; set; }
        public Nullable<decimal> Period04MovingAverageSales { get; set; }
        public Nullable<decimal> Period05MovingAverageSales { get; set; }
        public Nullable<decimal> Period06MovingAverageSales { get; set; }
        public Nullable<decimal> Period07MovingAverageSales { get; set; }
        public Nullable<decimal> Period08MovingAverageSales { get; set; }
        public Nullable<decimal> Period09MovingAverageSales { get; set; }
        public Nullable<decimal> Period10MovingAverageSales { get; set; }
        public string NewOrderRemarks { get; set; }
        public string NewOrderEmailAddress { get; set; }
        public string ShowRemarksInCustEmail { get; set; }
    
        public virtual SalesRep SalesRep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
    }
}
