//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA2QBookSvc.DataAccessBDSPub
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPriceList
    {
        public int Id { get; set; }
        public Nullable<int> ProductGroupCode { get; set; }
        public string ProductCode { get; set; }
        public string EachExtensionCode { get; set; }
        public int CustomerNumber { get; set; }
        public string ProductDescription { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> PendingSellingPrice { get; set; }
        public Nullable<double> SalesRepCommissionRate { get; set; }
        public Nullable<decimal> MarkupDollarAmount { get; set; }
        public Nullable<double> MarkupPercentage { get; set; }
        public Nullable<decimal> CurrentSellingPrice { get; set; }
        public Nullable<System.DateTime> CurrentSellingPriceDate { get; set; }
        public Nullable<int> SalesRepNumber { get; set; }
        public string ProductGroupDescription { get; set; }
        public string PresentInSourceDBF { get; set; }
    }
}
