//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA2QBookSvc.DataAccessBDSPub
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProductSale
    {
        public int CustomerNumber { get; set; }
        public int ProductGroupCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductGroupDescription { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<decimal> CurrentSellingPrice { get; set; }
        public string SoldByDescription { get; set; }
        public string EachExtensionCode { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> LastSaleDate { get; set; }
    }
}
