//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA2QBookSvc.DataAccessBDSPub
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebugTrace
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string ClassAndMethod { get; set; }
        public string SeqID { get; set; }
        public string TextLine { get; set; }
        public string SessionId { get; set; }
        public string LoginUserName { get; set; }
        public string TraceEventCode { get; set; }
        public string TraceEventDescrip { get; set; }
        public string OriginIPAddress { get; set; }
        public string OriginIpForwardedFor { get; set; }
        public string CurrentUrl { get; set; }
        public string LoginName { get; set; }
        public string LoginUserRole { get; set; }
    }
}
