//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA2QBookSvc.DataAccessBDSPub
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesRep()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public int SalesRepNumber { get; set; }
        public string SalesRepName { get; set; }
        public Nullable<int> SalesRepSchedule { get; set; }
        public Nullable<double> SalesRepSplitCommission { get; set; }
        public string SalesRepPayCommission { get; set; }
        public Nullable<decimal> SalesRepSalesAmount { get; set; }
        public string SalesRepActive { get; set; }
        public Nullable<System.DateTime> SalesRepActiveStatusDate { get; set; }
        public string SalesRepRole { get; set; }
        public string SalesRepPassword { get; set; }
        public string SalesRepLoginName { get; set; }
        public string PresentInSourceDBF { get; set; }
        public string CurrentActivityOriginIPAddress { get; set; }
        public Nullable<System.DateTime> CurrentActivityLastDateTime { get; set; }
        public string CurrentActivitySessionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
