//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA2QBookSvc.DataAccessBDSPub
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHistoryDetail
    {
        public int Id { get; set; }
        public int SalesRepNumber { get; set; }
        public int CustomerNumber { get; set; }
        public int BillToCustomer { get; set; }
        public int InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int InvoiceDateYear { get; set; }
        public int InvoiceDateWeekOfYear { get; set; }
        public int SalesOrderNumber { get; set; }
        public System.DateTime DateSalesOrderEntered { get; set; }
        public System.DateTime DateDeliveryRequired { get; set; }
        public System.DateTime DateDelivered { get; set; }
        public int DateDeliveredYear { get; set; }
        public int DateDeliveredWeekOfYear { get; set; }
        public int DetailLineNumber { get; set; }
        public string SalesOrderReceivedBy { get; set; }
        public int SalesRepNumberOriginal { get; set; }
        public string ShipToCompanyName { get; set; }
        public int DeliveryRoute { get; set; }
        public int DeliveryRouteStop { get; set; }
        public int ProductGroupCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductDescription { get; set; }
        public double QuantityOrdered { get; set; }
        public double QuantityShipped { get; set; }
        public double CasesOrdered { get; set; }
        public double CasesShipped { get; set; }
        public string CaseDescription { get; set; }
        public string PricingUnitOfMeas { get; set; }
        public decimal CostPerUnit { get; set; }
        public decimal PricePerUnit { get; set; }
        public decimal CostExtended { get; set; }
        public decimal PriceExtended { get; set; }
        public double CostingWeight { get; set; }
        public double PricingWeight { get; set; }
        public double SalesRepCommissionRate { get; set; }
        public double SalesRepSplitCommRate { get; set; }
        public int SalesRepForSplitComm { get; set; }
        public decimal BaseCommissionExtended { get; set; }
        public decimal SplitCommissionExtended { get; set; }
        public double SalesTaxRate { get; set; }
        public string SalesTaxAuthority { get; set; }
        public string SaleIsTaxable { get; set; }
        public decimal SalesTaxAmt { get; set; }
        public string DetailLineVoided { get; set; }
    }
}
