//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA2QBookSvc.DataAccessBDSPub
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDetail
    {
        public int Id { get; set; }
        public int SalesOrderNumber { get; set; }
        public int DetailLineNumber { get; set; }
        public Nullable<double> QuantityOrdered { get; set; }
        public Nullable<double> QuantityShipped { get; set; }
        public Nullable<double> CasesOrdered { get; set; }
        public Nullable<double> CasesShipped { get; set; }
        public string CaseDescription { get; set; }
        public string ProductCode { get; set; }
        public string ProductDescription { get; set; }
        public string DetailLineComment { get; set; }
        public Nullable<double> SalesRepCommissionRate { get; set; }
        public Nullable<decimal> ExtendedCommisionAmount { get; set; }
        public Nullable<int> ProductGroupCode { get; set; }
        public string PricingUnitOfMeas { get; set; }
        public Nullable<double> PricigUnits { get; set; }
        public Nullable<decimal> CostPerUnit { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<decimal> CostExtended { get; set; }
        public Nullable<decimal> PriceExtended { get; set; }
        public Nullable<decimal> CostingWeight { get; set; }
        public Nullable<decimal> PricingWeight { get; set; }
        public Nullable<int> SalesOrderHeaderId { get; set; }
        public Nullable<int> ProductsId { get; set; }
        public string PresentInSourceDBF { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesOrderHeader SalesOrderHeader { get; set; }
    }
}
