//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA2QBookSvc.DataAccessBDSPub
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime UserSetupDate { get; set; }
        public string UserIsInactive { get; set; }
        public System.DateTime UserInactiveDate { get; set; }
        public int CustomerNumber { get; set; }
        public int SalesRepNumber { get; set; }
        public string Password { get; set; }
        public string PasswordOld01 { get; set; }
        public System.DateTime PasswordSetDate { get; set; }
        public System.DateTime PasswordExpirationDate { get; set; }
    }
}
